### ISSUE TITLE
Wrong yaw in ellipse pose

### ISSUE THREAD

**Issue by JimmyDaSilva** [v4r-tuwien/v4r_ros#5]
Hi all,

I am simulating a peg-in-hole application in gazebo and need to find the pose of a hole.
The v4r_ellipse package is awesome but I have a small shift on the yaw angle:
![finding_holes](https://cloud.githubusercontent.com/assets/5452370/15936322/e1fb2bf8-2e6a-11e6-8971-0e270801aac8.png)

Does anyone have a similar issue ?

Thank you for the help

**Comment by maxbader** [comment]
a single ellipse detection has multiple solutions (eight) four in front of the camera :-)
Can it be that you are perceiving a one of them ?

**Comment by JimmyDaSilva** [comment]
@maxbader Thanks for the reply :)
Eight ? I thought the solution would be a cone intersected by a plane to get the desired radius. So two solutions, one behind the camera, another in the front.

Can you explain how you compute the solutions ? I am having trouble finding it in the code.

Many thanks

**Comment by maxbader** [comment]
On the not description you will find a link to a paper, but you can also
check the book Multiple View Geometry in Computer Vision.
If you know the location of your plane on which you like detect the ellipse
you can reduce it to one solution.

Greetings

2016-06-10 11:01 GMT+02:00 Jimmy DA SILVA notifications@github.com:

> @maxbader https://github.com/maxbader Thanks for the reply :)
> Eight ? I thought the solution would be a cone intersected by a plane to
> get the desired radius. So two solutions, one behind the camera, another in
> the front.
> 
> Can you explain how you compute the solutions ? I am having trouble
> finding it in the code.
> 
> Many thanks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/v4r-tuwien/v4r_ros/issues/5#issuecomment-225129437,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAre-IzYVDXeQLNwREBB5sWnstYf9WXiks5qKSgEgaJpZM4IyIMf
> .

## 

Dipl.-Ing. Dr.tech. Markus Bader

Institute of Computer Aided Automation
Automation Systems Group
TECHNISCHE UNIVERSITÄT WIEN
Treitlstrasse 1 | 4. Floor | E183-1 | 1040 Wien
DVR-Nummer: 0005886
Tel. +43 (0)1 58801 - 18305
Skype: markus.bader.at.work
Fax. +43 (0)1 58801 - 18391
markus.bader@tuwien.ac.at | www.auto.tuwien.ac.at |
http://info.tuwien.ac.at/mbader/

**Comment by JimmyDaSilva** [comment]
Thanks. I didn't notice the note to the paper.
I am going to have a read then

**Comment by JimmyDaSilva** [comment]
Now I understand perfectly the job you did there. Well done sir @maxbader !

You were right there is 8 solutions overall, and 2 that are possible in our configuration.
I have checked out the `skip_second_tf` option to see the other solution and it is way better.

![finding_holes2](https://cloud.githubusercontent.com/assets/5452370/15963389/d9e7f764-2f11-11e6-8bf3-ab09a325f740.png)

Thanks again for your help and this amazing package!

**Comment by maxbader** [comment]
Just a hint, the my v4r pkgs are depricated and the new one are named tuw_*
for ubuntu 16.04 and Kinetic

2016-06-10 14:01 GMT+02:00 Jimmy DA SILVA notifications@github.com:

> Now I understand perfectly the job you did there. Well done sir @maxbader
> https://github.com/maxbader !
> 
> You were right there is 8 solutions overall, and 2 that are possible in
> our configuration.
> I have checked out the skip_second_tf option to see the other solution
> and it is way better.
> 
> [image: finding_holes2]
> https://cloud.githubusercontent.com/assets/5452370/15963389/d9e7f764-2f11-11e6-8bf3-ab09a325f740.png
> 
> Thanks again for your help and this amazing package!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/v4r-tuwien/v4r_ros/issues/5#issuecomment-225164078,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAre-AcoQuU2vdRuLGZhKA_mZV77_kdEks5qKVIFgaJpZM4IyIMf
> .

## 

Dipl.-Ing. Dr.tech. Markus Bader

Institute of Computer Aided Automation
Automation Systems Group
TECHNISCHE UNIVERSITÄT WIEN
Treitlstrasse 1 | 4. Floor | E183-1 | 1040 Wien
DVR-Nummer: 0005886
Tel. +43 (0)1 58801 - 18305
Skype: markus.bader.at.work
Fax. +43 (0)1 58801 - 18391
markus.bader@tuwien.ac.at | www.auto.tuwien.ac.at |
http://info.tuwien.ac.at/mbader/

**Comment by JimmyDaSilva** [comment]
Thank you for the hint!
I intend to stay on Ubuntu 14.04 and Indigo for now but I will switch if I move to Kinetic
